version: "3"

networks:
    my_network:
      driver: bridge

services:
  db:
    container_name: mysql_server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: python_db
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

# the image below is working, but I cannot make it "talk" with the db on the other image
#  web:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "5000:5000"
#    env_file:
#      - .env
#    networks:
#      - my_network
